import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAuthenticatedUser } from "@/server/auth/session";
import { financialToolRegistry } from "@/server/ai/tools/financial-tools";
import { toApiFailure, ForbiddenError, ValidationError } from "@/server/errors/app-error";
const writeTools = ["create_my_transaction", "update_my_transaction", "create_or_update_my_budget", "create_my_financial_goal", "update_my_financial_goal"] as const;
const requestSchema = z.object({ tool: z.enum(writeTools), input: z.record(z.unknown()) }).strict();
function resultMessage(tool: string, input: Record<string, unknown>) { const amount = typeof input.amount === "number" ? `₹${input.amount.toLocaleString("en-IN")}` : ""; const category = typeof input.category === "string" ? input.category : "selected category"; if (tool === "create_my_transaction") return `Transaction added successfully: ${amount} ${category} ${String(input.type ?? "")} on ${String(input.date ?? "the selected date")}.`; if (tool === "update_my_transaction") return "Transaction updated successfully."; if (tool === "create_or_update_my_budget") return `Budget saved successfully: ${amount} for ${category} in ${String(input.month ?? "the selected period")}.`; if (tool === "create_my_financial_goal") return `Financial goal "${String(input.name ?? "Goal")}" created successfully with target ₹${typeof input.targetAmount === "number" ? input.targetAmount.toLocaleString("en-IN") : ""}.`; return "Financial goal updated successfully."; }
export async function POST(request: Request) { try { const body = requestSchema.safeParse(await request.json()); if (!body.success) throw new ValidationError("Invalid action confirmation."); const user = await requireAuthenticatedUser(); const data = await financialToolRegistry.execute(body.data.tool, body.data.input, { user }); return NextResponse.json({ ok: true, data: { tool: body.data.tool, result: data, message: resultMessage(body.data.tool, body.data.input) } }); } catch (error) { const body = toApiFailure(error); return NextResponse.json(body, { status: error instanceof ForbiddenError ? 403 : error instanceof Error && "status" in error ? (error as { status: number }).status : 500 }); } }
