CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash CHAR(64) UNIQUE NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX sessions_token_active_idx ON sessions(token_hash) WHERE revoked_at IS NULL;
CREATE TABLE categories (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('income','expense')));
CREATE UNIQUE INDEX categories_private_name_type_idx ON categories(user_id, lower(name), type) WHERE user_id IS NOT NULL;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY categories_tenant_visibility ON categories FOR ALL USING (user_id IS NULL OR user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
INSERT INTO categories (name, type) VALUES ('Housing','expense'),('Groceries','expense'),('Transport','expense'),('Utilities','expense'),('Healthcare','expense'),('Dining','expense'),('Entertainment','expense'),('Salary','income'),('Freelance','income'),('Investment','income'),('Other income','income') ON CONFLICT DO NOTHING;
CREATE TABLE transactions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, category_id UUID NOT NULL REFERENCES categories(id), type TEXT NOT NULL CHECK(type IN ('income','expense')), amount_cents BIGINT NOT NULL CHECK(amount_cents > 0), description TEXT NOT NULL, occurred_on DATE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE budgets (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, category_id UUID NOT NULL REFERENCES categories(id), month TEXT NOT NULL CHECK(month ~ '^\d{4}-(0[1-9]|1[0-2])$'), amount_cents BIGINT NOT NULL CHECK(amount_cents > 0), UNIQUE(user_id, category_id, month));
CREATE INDEX transactions_user_date_idx ON transactions(user_id, occurred_on DESC);
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY transactions_tenant_isolation ON transactions FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY budgets_tenant_isolation ON budgets FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE TABLE goals (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, target_amount_cents BIGINT NOT NULL CHECK(target_amount_cents > 0), current_saved_cents BIGINT NOT NULL DEFAULT 0 CHECK(current_saved_cents >= 0), target_date DATE NOT NULL, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX goals_user_date_idx ON goals(user_id, target_date ASC);
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY goals_tenant_isolation ON goals FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
