import "server-only";
import type { Pool } from "pg";
import type { Budget, Category, FinancialSummary, Goal, Transaction, TransactionListFilters } from "@/types/domain";
import type { AnalyticsRepository, BudgetRepository, CategoryRepository, GoalRepository, TransactionRepository } from "@/server/db/repositories";

type TransactionRow = { id: string; userId: string; categoryId: string; type: "income" | "expense"; amountCents: string; description: string; occurredOn: string; };
const transactionColumns = "id, user_id AS \"userId\", category_id AS \"categoryId\", type, amount_cents AS \"amountCents\", description, occurred_on AS \"occurredOn\"";
function mapTransaction(row: TransactionRow): Transaction { return { ...row, amountCents: Number(row.amountCents) }; }
export class PostgresTransactionRepository implements TransactionRepository {
  constructor(private readonly pool: Pool) {}
  async create(userId: string, input: Omit<Transaction, "id" | "userId">) { const result = await this.pool.query<TransactionRow>(`INSERT INTO transactions (user_id, category_id, type, amount_cents, description, occurred_on) VALUES ($1,$2,$3,$4,$5,$6) RETURNING ${transactionColumns}`, [userId, input.categoryId, input.type, input.amountCents, input.description, input.occurredOn]); return mapTransaction(result.rows[0]); }
  async listForUser(userId: string, filters: TransactionListFilters, limit: number) { const values: unknown[] = [userId]; const conditions = ["user_id = $1"]; if (filters.type) { values.push(filters.type); conditions.push(`type = $${values.length}`); } if (filters.categoryId) { values.push(filters.categoryId); conditions.push(`category_id = $${values.length}`); } if (filters.query) { values.push(`%${filters.query}%`); conditions.push(`description ILIKE $${values.length}`); } if (filters.startDate) { values.push(filters.startDate); conditions.push(`occurred_on >= $${values.length}`); } if (filters.endDate) { values.push(filters.endDate); conditions.push(`occurred_on <= $${values.length}`); } values.push(limit); const order = { newest: "occurred_on DESC, created_at DESC", oldest: "occurred_on ASC, created_at ASC", amount_desc: "amount_cents DESC", amount_asc: "amount_cents ASC" }[filters.sort ?? "newest"]; const result = await this.pool.query<TransactionRow>(`SELECT ${transactionColumns} FROM transactions WHERE ${conditions.join(" AND ")} ORDER BY ${order} LIMIT $${values.length}`, values); return result.rows.map(mapTransaction); }
  async findForUser(userId: string, transactionId: string) { const result = await this.pool.query<TransactionRow>(`SELECT ${transactionColumns} FROM transactions WHERE id = $1 AND user_id = $2`, [transactionId, userId]); return result.rows[0] ? mapTransaction(result.rows[0]) : null; }
  async updateForUser(userId: string, transactionId: string, input: Partial<Omit<Transaction, "id" | "userId">>) { const fields: Array<[string, unknown]> = [["category_id", input.categoryId], ["type", input.type], ["amount_cents", input.amountCents], ["description", input.description], ["occurred_on", input.occurredOn]].filter(([, value]) => value !== undefined) as Array<[string, unknown]>; const values = fields.map(([, value]) => value); values.push(transactionId, userId); const assignments = fields.map(([name], index) => `${name} = $${index + 1}`).join(", "); const result = await this.pool.query<TransactionRow>(`UPDATE transactions SET ${assignments} WHERE id = $${values.length - 1} AND user_id = $${values.length} RETURNING ${transactionColumns}`, values); return result.rows[0] ? mapTransaction(result.rows[0]) : null; }
  async deleteForUser(userId: string, transactionId: string) { const result = await this.pool.query("DELETE FROM transactions WHERE id = $1 AND user_id = $2", [transactionId, userId]); return result.rowCount === 1; }
  async summaryForUser(userId: string, month: string): Promise<FinancialSummary> { const result = await this.pool.query<{ income: string; expense: string }>("SELECT COALESCE(SUM(amount_cents) FILTER (WHERE type = 'income'),0) AS income, COALESCE(SUM(amount_cents) FILTER (WHERE type = 'expense'),0) AS expense FROM transactions WHERE user_id = $1 AND to_char(occurred_on, 'YYYY-MM') = $2", [userId, month]); const row = result.rows[0]; const incomeCents = Number(row.income); const expenseCents = Number(row.expense); return { month, incomeCents, expenseCents, netCents: incomeCents - expenseCents }; }
}
type CategoryRow = { id: string; userId: string | null; name: string; type: "income" | "expense"; };
export class PostgresCategoryRepository implements CategoryRepository {
  constructor(private readonly pool: Pool) {}
  async listAvailableToUser(userId: string) { const result = await this.pool.query<CategoryRow>("SELECT id, user_id AS \"userId\", name, type FROM categories WHERE user_id IS NULL OR user_id = $1 ORDER BY type, name", [userId]); return result.rows; }
  async findAvailableToUser(userId: string, categoryId: string) { const result = await this.pool.query<CategoryRow>("SELECT id, user_id AS \"userId\", name, type FROM categories WHERE id = $1 AND (user_id IS NULL OR user_id = $2)", [categoryId, userId]); return result.rows[0] ?? null; }
  async createForUser(userId: string, input: Omit<Category, "id" | "userId">) { const result = await this.pool.query<CategoryRow>("INSERT INTO categories (user_id, name, type) VALUES ($1,$2,$3) RETURNING id, user_id AS \"userId\", name, type", [userId, input.name, input.type]); return result.rows[0]; }
  async updatePrivateForUser(userId: string, categoryId: string, input: Partial<Pick<Category, "name" | "type">>) { const fields = Object.entries(input).filter(([, value]) => value !== undefined); if (!fields.length) return null; const column = fields[0][0] === "name" ? "name" : "type"; const result = await this.pool.query<CategoryRow>(`UPDATE categories SET ${column} = $1 WHERE id = $2 AND user_id = $3 RETURNING id, user_id AS \"userId\", name, type`, [fields[0][1], categoryId, userId]); return result.rows[0] ?? null; }
  async deletePrivateForUser(userId: string, categoryId: string) { const result = await this.pool.query("DELETE FROM categories WHERE id = $1 AND user_id = $2", [categoryId, userId]); return result.rowCount === 1; }
}
type BudgetRow = { id: string; userId: string; categoryId: string; month: string; amountCents: string; };
const budgetColumns = "id, user_id AS \"userId\", category_id AS \"categoryId\", month, amount_cents AS \"amountCents\"";
function mapBudget(row: BudgetRow): Budget { return { ...row, amountCents: Number(row.amountCents) }; }
export class PostgresBudgetRepository implements BudgetRepository {
  constructor(private readonly pool: Pool) {}
  async createForUser(userId: string, input: Omit<Budget, "id" | "userId">) { const result = await this.pool.query<BudgetRow>(`INSERT INTO budgets (user_id, category_id, month, amount_cents) VALUES ($1,$2,$3,$4) RETURNING ${budgetColumns}`, [userId, input.categoryId, input.month, input.amountCents]); return mapBudget(result.rows[0]); }
  async listForUserMonth(userId: string, month: string) { const result = await this.pool.query<BudgetRow>(`SELECT ${budgetColumns} FROM budgets WHERE user_id = $1 AND month = $2 ORDER BY category_id`, [userId, month]); return result.rows.map(mapBudget); }
  async findForUser(userId: string, budgetId: string) { const result = await this.pool.query<BudgetRow>(`SELECT ${budgetColumns} FROM budgets WHERE id = $1 AND user_id = $2`, [budgetId, userId]); return result.rows[0] ? mapBudget(result.rows[0]) : null; }
  async findByCategoryPeriod(userId: string, categoryId: string, month: string) { const result = await this.pool.query<BudgetRow>(`SELECT ${budgetColumns} FROM budgets WHERE user_id = $1 AND category_id = $2 AND month = $3`, [userId, categoryId, month]); return result.rows[0] ? mapBudget(result.rows[0]) : null; }
  async updateForUser(userId: string, budgetId: string, input: Pick<Budget, "amountCents">) { const result = await this.pool.query<BudgetRow>(`UPDATE budgets SET amount_cents = $1 WHERE id = $2 AND user_id = $3 RETURNING ${budgetColumns}`, [input.amountCents, budgetId, userId]); return result.rows[0] ? mapBudget(result.rows[0]) : null; }
  async deleteForUser(userId: string, budgetId: string) { const result = await this.pool.query("DELETE FROM budgets WHERE id = $1 AND user_id = $2", [budgetId, userId]); return result.rowCount === 1; }
  async spentForUserCategoryMonth(userId: string, categoryId: string, month: string) { const result = await this.pool.query<{ spent: string }>("SELECT COALESCE(SUM(amount_cents), 0) AS spent FROM transactions WHERE user_id = $1 AND category_id = $2 AND type = 'expense' AND to_char(occurred_on, 'YYYY-MM') = $3", [userId, categoryId, month]); return Number(result.rows[0].spent); }
}
export class PostgresAnalyticsRepository implements AnalyticsRepository {
  constructor(private readonly pool: Pool) {}
  async totalsForUserPeriod(userId: string, month: string) { const result = await this.pool.query<{ income: string; expense: string }>("SELECT COALESCE(SUM(amount_cents) FILTER (WHERE type = 'income'),0) AS income, COALESCE(SUM(amount_cents) FILTER (WHERE type = 'expense'),0) AS expense FROM transactions WHERE user_id = $1 AND to_char(occurred_on, 'YYYY-MM') = $2", [userId, month]); return { incomeCents: Number(result.rows[0].income), expenseCents: Number(result.rows[0].expense) }; }
  async categorySpendingForUserPeriod(userId: string, month: string) { const result = await this.pool.query<{ categoryId: string; categoryName: string; amountCents: string }>("SELECT t.category_id AS \"categoryId\", c.name AS \"categoryName\", SUM(t.amount_cents) AS \"amountCents\" FROM transactions t JOIN categories c ON c.id = t.category_id WHERE t.user_id = $1 AND t.type = 'expense' AND to_char(t.occurred_on, 'YYYY-MM') = $2 GROUP BY t.category_id, c.name ORDER BY SUM(t.amount_cents) DESC", [userId, month]); return result.rows.map((row) => ({ ...row, amountCents: Number(row.amountCents) })); }
  async largestExpensesForUserPeriod(userId: string, month: string, limit: number) { const result = await this.pool.query<TransactionRow>(`SELECT ${transactionColumns} FROM transactions WHERE user_id = $1 AND type = 'expense' AND to_char(occurred_on, 'YYYY-MM') = $2 ORDER BY amount_cents DESC LIMIT $3`, [userId, month, limit]); return result.rows.map(mapTransaction); }
  async expenseTotalForUserPeriod(userId: string, month: string) { const result = await this.pool.query<{ amount: string }>("SELECT COALESCE(SUM(amount_cents),0) AS amount FROM transactions WHERE user_id = $1 AND type = 'expense' AND to_char(occurred_on, 'YYYY-MM') = $2", [userId, month]); return Number(result.rows[0].amount); }
}
type GoalRow = { id: string; userId: string; name: string; targetAmountCents: string; currentSavedCents: string; targetDate: string; description: string | null; createdAt?: string; };
const goalColumns = "id, user_id AS \"userId\", name, target_amount_cents AS \"targetAmountCents\", current_saved_cents AS \"currentSavedCents\", to_char(target_date, 'YYYY-MM-DD') AS \"targetDate\", description, created_at AS \"createdAt\"";
function mapGoal(row: GoalRow): Goal { return { ...row, targetAmountCents: Number(row.targetAmountCents), currentSavedCents: Number(row.currentSavedCents) }; }
export class PostgresGoalRepository implements GoalRepository {
  constructor(private readonly pool: Pool) {}
  async create(userId: string, input: Omit<Goal, "id" | "userId" | "createdAt">): Promise<Goal> { const result = await this.pool.query<GoalRow>(`INSERT INTO goals (user_id, name, target_amount_cents, current_saved_cents, target_date, description) VALUES ($1,$2,$3,$4,$5,$6) RETURNING ${goalColumns}`, [userId, input.name, input.targetAmountCents, input.currentSavedCents ?? 0, input.targetDate, input.description ?? null]); return mapGoal(result.rows[0]); }
  async listForUser(userId: string): Promise<Goal[]> { const result = await this.pool.query<GoalRow>(`SELECT ${goalColumns} FROM goals WHERE user_id = $1 ORDER BY target_date ASC, created_at ASC`, [userId]); return result.rows.map(mapGoal); }
  async findForUser(userId: string, goalId: string): Promise<Goal | null> { const result = await this.pool.query<GoalRow>(`SELECT ${goalColumns} FROM goals WHERE id = $1 AND user_id = $2`, [goalId, userId]); return result.rows[0] ? mapGoal(result.rows[0]) : null; }
  async updateForUser(userId: string, goalId: string, input: Partial<Omit<Goal, "id" | "userId" | "createdAt">>): Promise<Goal | null> { const fields: Array<[string, unknown]> = [["name", input.name], ["target_amount_cents", input.targetAmountCents], ["current_saved_cents", input.currentSavedCents], ["target_date", input.targetDate], ["description", input.description]].filter(([, value]) => value !== undefined) as Array<[string, unknown]>; if (!fields.length) return this.findForUser(userId, goalId); const values = fields.map(([, value]) => value); values.push(goalId, userId); const assignments = fields.map(([name], index) => `${name} = $${index + 1}`).join(", "); const result = await this.pool.query<GoalRow>(`UPDATE goals SET ${assignments} WHERE id = $${values.length - 1} AND user_id = $${values.length} RETURNING ${goalColumns}`, values); return result.rows[0] ? mapGoal(result.rows[0]) : null; }
  async deleteForUser(userId: string, goalId: string): Promise<boolean> { const result = await this.pool.query("DELETE FROM goals WHERE id = $1 AND user_id = $2", [goalId, userId]); return result.rowCount === 1; }
}

