import "server-only";
import { z } from "zod";
import { getDatabasePool } from "@/server/db/pool";
import { PostgresAnalyticsRepository, PostgresBudgetRepository, PostgresCategoryRepository, PostgresGoalRepository, PostgresTransactionRepository } from "@/server/db/postgres-repositories";
import { AnalyticsService } from "@/server/services/analytics-service";
import { BudgetService } from "@/server/services/budget-service";
import { TransactionService } from "@/server/services/transaction-service";
import { CategoryService } from "@/server/services/category-service";
import { GoalService } from "@/server/services/goal-service";
import { ToolRegistry } from "@/server/ai/tool-registry";
import type { ToolContext } from "@/types/ai";
const month = z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/);
const date = z.string().date();
const jsonObject = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
export interface FinancialToolServices { transactions: TransactionService; budgets: BudgetService; analytics: AnalyticsService; categories: CategoryService; goals: GoalService; }
function defaultServices(context: ToolContext): FinancialToolServices { const pool = getDatabasePool(); const currentUser = async () => context.user; const categories = new PostgresCategoryRepository(pool); const budgets = new PostgresBudgetRepository(pool); const analytics = new AnalyticsService(new PostgresAnalyticsRepository(pool), budgets, categories, currentUser); const goals = new PostgresGoalRepository(pool); return { transactions: new TransactionService(new PostgresTransactionRepository(pool), categories, currentUser), budgets: new BudgetService(budgets, categories, currentUser), analytics, categories: new CategoryService(categories, currentUser), goals: new GoalService(goals, analytics, currentUser) }; }
export function createFinancialToolRegistry(servicesForContext: (context: ToolContext) => FinancialToolServices = defaultServices) { const registry = new ToolRegistry();
  registry.register({ name: "get_my_transactions", description: "List the authenticated user's transactions with optional date, category, type, and limit filters.", schema: z.object({ startDate: date.optional(), endDate: date.optional(), categoryId: z.string().uuid().optional(), type: z.enum(["income", "expense"]).optional(), limit: z.number().int().min(1).max(100).default(25) }).refine((value) => !value.startDate || !value.endDate || value.startDate <= value.endDate), jsonSchema: jsonObject({ startDate: { type: "string", format: "date" }, endDate: { type: "string", format: "date" }, categoryId: { type: "string", format: "uuid" }, type: { type: "string", enum: ["income", "expense"] }, limit: { type: "integer", minimum: 1, maximum: 100 } }), execute: (input, context) => servicesForContext(context).transactions.listForCurrentUser({ startDate: input.startDate, endDate: input.endDate, categoryId: input.categoryId, type: input.type }, input.limit) });
  registry.register({ name: "get_my_financial_summary", description: "Get income, expenses, savings, and savings rate for the authenticated user and a month.", schema: z.object({ period: month }), jsonSchema: jsonObject({ period: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" } }, ["period"]), execute: (input, context) => servicesForContext(context).analytics.getFinancialSummary(context.user, input.period) });
  registry.register({ name: "get_my_category_spending", description: "Get authenticated-user expense totals and shares by category for a month.", schema: z.object({ period: month }), jsonSchema: jsonObject({ period: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" } }, ["period"]), execute: (input, context) => servicesForContext(context).analytics.getCategoryBreakdown(context.user, input.period) });
  registry.register({ name: "get_my_spending_trends", description: "Compare the authenticated user's spending across recent monthly periods.", schema: z.object({ period: month, comparisonPeriods: z.number().int().min(1).max(6).default(1) }), jsonSchema: jsonObject({ period: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" }, comparisonPeriods: { type: "integer", minimum: 1, maximum: 6 } }, ["period"]), execute: async (input, context) => { const service = servicesForContext(context).analytics; const result = []; let cursor = input.period; for (let index = 0; index < (input.comparisonPeriods ?? 1); index += 1) { result.push(await service.getSpendingTrends(context.user, cursor)); const [year, value] = cursor.split("-").map(Number); const prior = new Date(Date.UTC(year, value - 2, 1)); cursor = `${prior.getUTCFullYear()}-${String(prior.getUTCMonth() + 1).padStart(2, "0")}`; } return result; } });
  registry.register({ name: "get_my_budget_status", description: "Get the authenticated user's budget status for a month, optionally for one category.", schema: z.object({ month, categoryId: z.string().uuid().optional() }), jsonSchema: jsonObject({ month: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" }, categoryId: { type: "string", format: "uuid" } }, ["month"]), execute: async (input, context) => { const statuses = await servicesForContext(context).budgets.listStatusesForUser(context.user, input.month); return input.categoryId ? statuses.filter((item) => item.category.id === input.categoryId) : statuses; } });
  registry.register({ name: "create_my_transaction", description: "Create an income or expense transaction for the authenticated user. Supply a category name or ID.", schema: z.object({ type: z.enum(["income", "expense"]), amount: z.number().positive().max(1_000_000), categoryId: z.string().uuid().optional(), category: z.string().trim().min(1).max(60).optional(), description: z.string().trim().min(1).max(255), date }).strict().refine((value) => Boolean(value.categoryId || value.category), "A category is required."), jsonSchema: jsonObject({ type: { type: "string", enum: ["income", "expense"] }, amount: { type: "number", minimum: 0.01 }, categoryId: { type: "string", format: "uuid" }, category: { type: "string" }, description: { type: "string", minLength: 1, maxLength: 255 }, date: { type: "string", format: "date" } }, ["type", "amount", "description", "date"]), execute: async (input, context) => { const services = servicesForContext(context); const categoryId = input.categoryId ?? (await services.categories.resolveForCurrentUser(input.category!, input.type)).id; return services.transactions.createForCurrentUser({ type: input.type, amountCents: Math.round(input.amount * 100), categoryId, description: input.description, occurredOn: input.date }); } });
  registry.register({ name: "update_my_transaction", description: "Update fields of an authenticated user's existing transaction.", schema: z.object({ transactionId: z.string().uuid(), type: z.enum(["income", "expense"]).optional(), amount: z.number().positive().max(1_000_000).optional(), categoryId: z.string().uuid().optional(), description: z.string().trim().min(1).max(255).optional(), date: date.optional() }).strict().refine((value) => value.type !== undefined || value.amount !== undefined || value.categoryId !== undefined || value.description !== undefined || value.date !== undefined), jsonSchema: jsonObject({ transactionId: { type: "string", format: "uuid" }, type: { type: "string", enum: ["income", "expense"] }, amount: { type: "number", minimum: 0.01 }, categoryId: { type: "string", format: "uuid" }, description: { type: "string" }, date: { type: "string", format: "date" } }, ["transactionId"]), execute: (input, context) => servicesForContext(context).transactions.updateForCurrentUser(input.transactionId, { type: input.type, amountCents: input.amount === undefined ? undefined : Math.round(input.amount * 100), categoryId: input.categoryId, description: input.description, occurredOn: input.date }) });
  registry.register({ name: "create_or_update_my_budget", description: "Create or update an authenticated user's expense-category budget for a month. Supply a category name or ID.", schema: z.object({ categoryId: z.string().uuid().optional(), category: z.string().trim().min(1).max(60).optional(), amount: z.number().positive().max(1_000_000), month }).strict().refine((value) => Boolean(value.categoryId || value.category), "A category is required."), jsonSchema: jsonObject({ categoryId: { type: "string", format: "uuid" }, category: { type: "string" }, amount: { type: "number", minimum: 0.01 }, month: { type: "string", pattern: "^\\d{4}-(0[1-9]|1[0-2])$" } }, ["amount", "month"]), execute: async (input, context) => { const services = servicesForContext(context); const categoryId = input.categoryId ?? (await services.categories.resolveForCurrentUser(input.category!, "expense")).id; return services.budgets.createOrUpdateForCurrentUser({ categoryId, amountCents: Math.round(input.amount * 100), month: input.month }); } });
  registry.register({ name: "get_my_financial_goals", description: "List all active savings goals for the authenticated user, including target amount, saved amount, deadline, remaining amount, and required monthly savings.", schema: z.object({}).strict(), jsonSchema: jsonObject({}), execute: (_input, context) => servicesForContext(context).goals.listStatusesForCurrentUser() });
  registry.register({ name: "get_my_goal_action_plan", description: "Get a deterministic monthly action plan for a financial goal (or user's first goal if goalId is omitted). Returns remaining amount, remaining months, required average monthly savings, current savings pace, and top adjustable spending categories.", schema: z.object({ goalId: z.string().uuid().optional() }).strict(), jsonSchema: jsonObject({ goalId: { type: "string", format: "uuid" } }), execute: async (input, context) => { const services = servicesForContext(context); let targetGoalId = input.goalId; if (!targetGoalId) { const list = await services.goals.listForCurrentUser(); if (!list.length) return { message: "You have not set any financial goals yet. You can create one to start tracking." }; targetGoalId = list[0].id; } return services.goals.getActionPlanForCurrentUser(targetGoalId); } });
  registry.register({ name: "create_my_financial_goal", description: "Create a new savings goal for the authenticated user with name, target amount (in decimal currency/rupees), initial saved amount, target date, and optional description.", schema: z.object({ name: z.string().trim().min(1).max(100), targetAmount: z.number().positive().max(10_000_000), currentSaved: z.number().min(0).max(10_000_000).optional().default(0), targetDate: date, description: z.string().trim().max(500).optional() }).strict(), jsonSchema: jsonObject({ name: { type: "string", minLength: 1, maxLength: 100 }, targetAmount: { type: "number", minimum: 1 }, currentSaved: { type: "number", minimum: 0 }, targetDate: { type: "string", format: "date" }, description: { type: "string", maxLength: 500 } }, ["name", "targetAmount", "targetDate"]), execute: (input, context) => servicesForContext(context).goals.createForCurrentUser({ name: input.name, targetAmountCents: Math.round(input.targetAmount * 100), currentSavedCents: Math.round((input.currentSaved ?? 0) * 100), targetDate: input.targetDate, description: input.description }) });
  registry.register({ name: "update_my_financial_goal", description: "Update an existing savings goal or record a contribution to it.", schema: z.object({ goalId: z.string().uuid(), name: z.string().trim().min(1).max(100).optional(), targetAmount: z.number().positive().max(10_000_000).optional(), currentSaved: z.number().min(0).max(10_000_000).optional(), addSavedAmount: z.number().positive().max(10_000_000).optional(), targetDate: date.optional(), description: z.string().trim().max(500).optional() }).strict().refine((val) => val.name !== undefined || val.targetAmount !== undefined || val.currentSaved !== undefined || val.addSavedAmount !== undefined || val.targetDate !== undefined || val.description !== undefined, "At least one update field is required."), jsonSchema: jsonObject({ goalId: { type: "string", format: "uuid" }, name: { type: "string" }, targetAmount: { type: "number", minimum: 1 }, currentSaved: { type: "number", minimum: 0 }, addSavedAmount: { type: "number", minimum: 1 }, targetDate: { type: "string", format: "date" }, description: { type: "string" } }, ["goalId"]), execute: async (input, context) => { const services = servicesForContext(context); if (input.addSavedAmount !== undefined) { return services.goals.contributeForCurrentUser(input.goalId, Math.round(input.addSavedAmount * 100)); } return services.goals.updateForCurrentUser(input.goalId, { name: input.name, targetAmountCents: input.targetAmount === undefined ? undefined : Math.round(input.targetAmount * 100), currentSavedCents: input.currentSaved === undefined ? undefined : Math.round(input.currentSaved * 100), targetDate: input.targetDate, description: input.description }); } });
  return registry;
}
export const financialToolRegistry = createFinancialToolRegistry();
