import "server-only";
import { requireAuthenticatedUser } from "@/server/auth/session";
import { getAnalyticsService, AnalyticsService } from "@/server/services/analytics-service";
import type { AuthenticatedUser, FinancialInsight } from "@/types/domain";
type CurrentUser = () => Promise<AuthenticatedUser>;
export interface InsightThresholds { categorySurgePercent: number; monthChangePercent: number; budgetApproachingPercent: number; savingsReductionPercent: number; }
export const DEFAULT_INSIGHT_THRESHOLDS: InsightThresholds = { categorySurgePercent: 25, monthChangePercent: 25, budgetApproachingPercent: 80, savingsReductionPercent: 20 };
function previousMonth(month: string) { const [year, current] = month.split("-").map(Number); const date = new Date(Date.UTC(year, current - 2, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; }
const rupees = (cents: number) => `₹${(cents / 100).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
export class InsightService {
  constructor(private readonly analytics: AnalyticsService, private readonly currentUser: CurrentUser = requireAuthenticatedUser, private readonly thresholds: InsightThresholds = DEFAULT_INSIGHT_THRESHOLDS) {}
  async getInsightsForCurrentUser(period: string) { return this.getInsights(await this.currentUser(), period); }
  async getInsights(user: AuthenticatedUser, period: string): Promise<FinancialInsight[]> {
    const prior = previousMonth(period); const [currentCategories, priorCategories, trend, budgets] = await Promise.all([this.analytics.getCategoryBreakdown(user, period), this.analytics.getCategoryBreakdown(user, prior), this.analytics.getSpendingTrends(user, period), this.analytics.getBudgetOverview(user, period)]); const insights: FinancialInsight[] = []; const oldCategories = new Map(priorCategories.map((item) => [item.categoryId, item]));
    for (const current of currentCategories) { const previous = oldCategories.get(current.categoryId); if (!previous || previous.amountCents === 0 || current.amountCents <= previous.amountCents) continue; const increase = current.amountCents - previous.amountCents; const percent = Math.round((increase / previous.amountCents) * 10000) / 100; if (percent >= this.thresholds.categorySurgePercent) { insights.push({ id: `surge-${current.categoryId}`, type: "category_surge", category: current.categoryName, currentValueCents: current.amountCents, previousValueCents: previous.amountCents, percentageChange: percent, severity: percent >= 50 ? "critical" : "warning", explanation: `${current.categoryName} spending increased by ${percent}% compared with the previous period.`, recommendation: `Review the ${rupees(increase)} increase and decide whether it is intentional.`, supportingFigures: [{ label: "Current spending", value: rupees(current.amountCents) }, { label: "Previous spending", value: rupees(previous.amountCents) }, { label: "Increase", value: rupees(increase) }] }); const target = Math.round(current.amountCents * (this.thresholds.savingsReductionPercent / 100)); insights.push({ id: `saving-${current.categoryId}`, type: "savings_opportunity", category: current.categoryName, currentValueCents: current.amountCents, previousValueCents: previous.amountCents, percentageChange: percent, severity: "info", explanation: `The recommendation uses a ${this.thresholds.savingsReductionPercent}% reduction target on current ${current.categoryName} spending after its increase.`, recommendation: `Reducing current ${current.categoryName} spending by ${this.thresholds.savingsReductionPercent}% would free about ${rupees(target)}; this is an assumption, not an optimal target.`, supportingFigures: [{ label: "Current spending", value: rupees(current.amountCents) }, { label: "Reduction target", value: `${this.thresholds.savingsReductionPercent}%` }, { label: "Estimated amount", value: rupees(target) }] }); } }
    for (const status of budgets) { if (status.exceeded) insights.push({ id: `overrun-${status.budget.id}`, type: "budget_overrun", category: status.category.name, currentValueCents: status.spentCents, previousValueCents: status.budget.amountCents, percentageChange: status.percentageUsed, severity: "critical", explanation: `${status.category.name} spending is ${status.percentageUsed}% of its budget.`, recommendation: `Spending is ${rupees(Math.abs(status.remainingCents))} above the set budget; consider pausing discretionary purchases in this category for the period.`, supportingFigures: [{ label: "Spent", value: rupees(status.spentCents) }, { label: "Budget", value: rupees(status.budget.amountCents) }, { label: "Over budget", value: rupees(Math.abs(status.remainingCents)) }] }); else if (status.percentageUsed >= this.thresholds.budgetApproachingPercent) insights.push({ id: `approaching-${status.budget.id}`, type: "budget_approaching", category: status.category.name, currentValueCents: status.spentCents, previousValueCents: status.budget.amountCents, percentageChange: status.percentageUsed, severity: "warning", explanation: `${status.category.name} has used ${status.percentageUsed}% of its budget, meeting the ${this.thresholds.budgetApproachingPercent}% alert threshold.`, recommendation: `There is ${rupees(status.remainingCents)} remaining in this category budget for the period.`, supportingFigures: [{ label: "Spent", value: rupees(status.spentCents) }, { label: "Budget", value: rupees(status.budget.amountCents) }, { label: "Remaining", value: rupees(status.remainingCents) }] }); }
    if (trend.changePercent !== null && Math.abs(trend.changePercent) >= this.thresholds.monthChangePercent) insights.push({ id: `month-change-${period}`, type: "month_over_month_change", category: null, currentValueCents: trend.expenseCents, previousValueCents: trend.previousExpenseCents, percentageChange: trend.changePercent, severity: trend.changePercent > 0 ? "warning" : "info", explanation: `Total spending ${trend.changePercent > 0 ? "increased" : "decreased"} by ${Math.abs(trend.changePercent)}% compared with the previous period.`, recommendation: trend.changePercent > 0 ? `Review the category changes behind the ${rupees(trend.changeCents)} increase.` : `Spending is ${rupees(Math.abs(trend.changeCents))} below the previous period; confirm this pattern is sustainable.`, supportingFigures: [{ label: "Current spending", value: rupees(trend.expenseCents) }, { label: "Previous spending", value: rupees(trend.previousExpenseCents) }, { label: "Change", value: rupees(Math.abs(trend.changeCents)) }] }); return insights;
  }
}
let insightService: InsightService | undefined;
export function getInsightService() { if (!insightService) insightService = new InsightService(getAnalyticsService()); return insightService; }
