import { describe, expect, it } from "vitest";
import { AnalyticsService } from "@/server/services/analytics-service";
import type { AnalyticsRepository, BudgetRepository, CategoryRepository } from "@/server/db/repositories";
import type { Budget, Category, Transaction } from "@/types/domain";
const food: Category = { id: "11111111-1111-4111-8111-111111111111", userId: null, name: "Food", type: "expense" };
class AnalyticsMemory implements AnalyticsRepository { async totalsForUserPeriod(userId: string) { return userId === "a" ? { incomeCents: 20_000, expenseCents: 8_000 } : { incomeCents: 0, expenseCents: 0 }; } async categorySpendingForUserPeriod(userId: string) { return userId === "a" ? [{ categoryId: food.id, categoryName: "Food", amountCents: 8_000 }] : []; } async largestExpensesForUserPeriod(userId: string): Promise<Transaction[]> { return userId === "a" ? [{ id: "t1", userId: "a", categoryId: food.id, type: "expense", amountCents: 5_000, description: "Groceries", occurredOn: "2026-09-01" }] : []; } async expenseTotalForUserPeriod(userId: string, month: string) { return userId === "a" ? (month === "2026-08" ? 4_000 : 8_000) : 0; } }
class BudgetMemory implements BudgetRepository { async createForUser(_: string, input: Omit<Budget, "id" | "userId">) { return { ...input, id: "new", userId: "a" }; } async listForUserMonth() { return []; } async findForUser() { return null; } async findByCategoryPeriod() { return null; } async updateForUser() { return null; } async deleteForUser() { return false; } async spentForUserCategoryMonth() { return 0; } }
class CategoryMemory implements CategoryRepository { async listAvailableToUser() { return [food]; } async findAvailableToUser(_: string, id: string) { return id === food.id ? food : null; } async createForUser(_: string, input: Omit<Category, "id" | "userId">) { return { ...input, id: "new", userId: "a" }; } async updatePrivateForUser() { return null; } async deletePrivateForUser() { return false; } }
describe("AnalyticsService", () => { it("calculates summary, category share, and month-over-month spending", async () => { const service = new AnalyticsService(new AnalyticsMemory(), new BudgetMemory(), new CategoryMemory(), async () => ({ id: "a", email: "a@test.dev" })); const result = await service.getDashboardForCurrentUser("2026-09"); expect(result.summary).toMatchObject({ incomeCents: 20_000, expenseCents: 8_000, netSavingsCents: 12_000, savingsRate: 60 }); expect(result.categoryBreakdown[0]).toMatchObject({ percentageOfExpenses: 100 }); expect(result.spendingTrend).toMatchObject({ previousExpenseCents: 4_000, changeCents: 4_000, changePercent: 100 }); }); it("returns safe empty analytics and never aggregates another user", async () => { const service = new AnalyticsService(new AnalyticsMemory(), new BudgetMemory(), new CategoryMemory(), async () => ({ id: "b", email: "b@test.dev" })); const result = await service.getDashboardForCurrentUser("2026-09"); expect(result.summary).toMatchObject({ incomeCents: 0, expenseCents: 0, netSavingsCents: 0, savingsRate: null }); expect(result.categoryBreakdown).toEqual([]); expect(result.largestTransactions).toEqual([]); }); });
