import { describe, expect, it } from "vitest";
import { BudgetService } from "@/server/services/budget-service";
import type { BudgetRepository, CategoryRepository } from "@/server/db/repositories";
import type { Budget, Category } from "@/types/domain";
const category: Category = { id: "11111111-1111-4111-8111-111111111111", userId: null, name: "Food", type: "expense" };
const income: Category = { id: "22222222-2222-4222-8222-222222222222", userId: null, name: "Salary", type: "income" };
const privateCategory: Category = { id: "33333333-3333-4333-8333-333333333333", userId: "user-a", name: "Private food", type: "expense" };
class MemoryCategories implements CategoryRepository { async listAvailableToUser(userId: string) { return [category, income, ...(userId === "user-a" ? [privateCategory] : [])]; } async findAvailableToUser(userId: string, id: string) { return (await this.listAvailableToUser(userId)).find((item) => item.id === id) ?? null; } async createForUser(_: string, input: Omit<Category, "id" | "userId">) { return { ...input, id: "created", userId: "user-a" }; } async updatePrivateForUser() { return null; } async deletePrivateForUser() { return false; } }
class MemoryBudgets implements BudgetRepository { rows: Budget[] = []; spent = 0; async createForUser(userId: string, input: Omit<Budget, "id" | "userId">) { const row = { ...input, userId, id: `budget-${this.rows.length + 1}` }; this.rows.push(row); return row; } async listForUserMonth(userId: string, month: string) { return this.rows.filter((row) => row.userId === userId && row.month === month); } async findForUser(userId: string, id: string) { return this.rows.find((row) => row.id === id && row.userId === userId) ?? null; } async findByCategoryPeriod(userId: string, categoryId: string, month: string) { return this.rows.find((row) => row.userId === userId && row.categoryId === categoryId && row.month === month) ?? null; } async updateForUser(userId: string, id: string, input: Pick<Budget, "amountCents">) { const row = await this.findForUser(userId, id); return row ? Object.assign(row, input) : null; } async deleteForUser(userId: string, id: string) { const index = this.rows.findIndex((row) => row.id === id && row.userId === userId); if (index < 0) return false; this.rows.splice(index, 1); return true; } async spentForUserCategoryMonth() { return this.spent; } }
const input = { categoryId: category.id, month: "2026-09", amountCents: 10_000 };
describe("BudgetService", () => { it("creates, updates, and deletes an owned budget", async () => { const repository = new MemoryBudgets(); const service = new BudgetService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); const budget = await service.createForCurrentUser(input); expect((await service.updateForCurrentUser(budget.id, { amountCents: 12_000 })).amountCents).toBe(12_000); await service.deleteForCurrentUser(budget.id); expect(await repository.findForUser("user-a", budget.id)).toBeNull(); }); it("rejects duplicate, invalid, foreign-category, and cross-user budget access", async () => { const repository = new MemoryBudgets(); const userA = new BudgetService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); const budget = await userA.createForCurrentUser(input); await expect(userA.createForCurrentUser(input)).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); await expect(userA.createForCurrentUser({ ...input, categoryId: income.id })).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); const userB = new BudgetService(repository, new MemoryCategories(), async () => ({ id: "user-b", email: "b@test.dev" })); await expect(userB.createForCurrentUser({ ...input, categoryId: privateCategory.id })).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); await expect(userB.updateForCurrentUser(budget.id, { amountCents: 1 })).rejects.toMatchObject({ code: "NOT_FOUND" }); }); it("calculates remaining percentage and exceeded state centrally", async () => { const repository = new MemoryBudgets(); repository.spent = 15_000; const service = new BudgetService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); await service.createForCurrentUser(input); const [status] = await service.listStatusesForCurrentUser("2026-09"); expect(status).toMatchObject({ spentCents: 15_000, remainingCents: -5_000, percentageUsed: 150, exceeded: true }); }); });
