import { describe, expect, it } from "vitest";
import { InsightService } from "@/server/services/insight-service";
import type { AnalyticsService } from "@/server/services/analytics-service";
import type { BudgetStatus, CategorySpending, SpendingTrend } from "@/types/domain";
const category: CategorySpending = { categoryId: "food", categoryName: "Shopping", amountCents: 870_000, percentageOfExpenses: 100 };
const previous: CategorySpending = { ...category, amountCents: 590_000 };
function analytics({ current = [category], prior = [previous], trend = { month: "2026-09", expenseCents: 870_000, previousExpenseCents: 590_000, changeCents: 280_000, changePercent: 47.46 } as SpendingTrend, budgets = [] as BudgetStatus[] } = {}) { return { getCategoryBreakdown: async (_: unknown, period: string) => period === "2026-08" ? prior : current, getSpendingTrends: async () => trend, getBudgetOverview: async () => budgets } as unknown as AnalyticsService; }
const user = async () => ({ id: "user-a", email: "a@test.dev" });
describe("InsightService", () => { it("creates grounded surge, savings, month-change, budget warning and overrun insights", async () => { const budget: BudgetStatus = { budget: { id: "b", userId: "user-a", categoryId: "food", month: "2026-09", amountCents: 1_000_000 }, category: { id: "food", userId: null, name: "Shopping", type: "expense" }, spentCents: 1_100_000, remainingCents: -100_000, percentageUsed: 110, exceeded: true }; const insights = await new InsightService(analytics({ budgets: [budget] }), user).getInsightsForCurrentUser("2026-09"); expect(insights.map((item) => item.type)).toEqual(expect.arrayContaining(["category_surge", "savings_opportunity", "month_over_month_change", "budget_overrun"])); expect(insights.find((item) => item.type === "category_surge")?.percentageChange).toBeCloseTo(47.46, 1); }); it("emits no comparison insights without a baseline, including new categories and zero spending", async () => { const zeroTrend: SpendingTrend = { month: "2026-09", expenseCents: 0, previousExpenseCents: 0, changeCents: 0, changePercent: null }; const insights = await new InsightService(analytics({ prior: [], trend: zeroTrend }), user).getInsightsForCurrentUser("2026-09"); expect(insights).toEqual([]); }); it("handles deleted categories, no budgets, and insufficient data without errors", async () => { const insights = await new InsightService(analytics({ current: [], prior: [previous], budgets: [], trend: { month: "2026-09", expenseCents: 0, previousExpenseCents: 0, changeCents: 0, changePercent: null } }), user).getInsightsForCurrentUser("2026-09"); expect(insights).toEqual([]); }); });
