import { describe, expect, it } from "vitest";
import { TransactionService } from "@/server/services/transaction-service";
import type { CategoryRepository, TransactionRepository } from "@/server/db/repositories";
import type { Category, FinancialSummary, Transaction, TransactionListFilters } from "@/types/domain";

const expense: Category = { id: "11111111-1111-4111-8111-111111111111", userId: null, name: "Groceries", type: "expense" };
const income: Category = { id: "22222222-2222-4222-8222-222222222222", userId: null, name: "Salary", type: "income" };
class MemoryCategories implements CategoryRepository { async listAvailableToUser() { return [expense, income]; } async findAvailableToUser(_: string, id: string) { return [expense, income].find((category) => category.id === id) ?? null; } async createForUser(_: string, input: Omit<Category, "id" | "userId">) { return { ...input, id: "created", userId: "user-a" }; } async updatePrivateForUser() { return null; } async deletePrivateForUser() { return false; } }
class MemoryTransactions implements TransactionRepository { rows: Transaction[] = []; async create(userId: string, input: Omit<Transaction, "id" | "userId">) { const row = { ...input, userId, id: `transaction-${this.rows.length + 1}` }; this.rows.push(row); return row; } async listForUser(userId: string, _: TransactionListFilters) { return this.rows.filter((row) => row.userId === userId); } async findForUser(userId: string, id: string) { return this.rows.find((row) => row.id === id && row.userId === userId) ?? null; } async updateForUser(userId: string, id: string, input: Partial<Omit<Transaction, "id" | "userId">>) { const row = await this.findForUser(userId, id); return row ? Object.assign(row, input) : null; } async deleteForUser(userId: string, id: string) { const index = this.rows.findIndex((row) => row.id === id && row.userId === userId); if (index < 0) return false; this.rows.splice(index, 1); return true; } async summaryForUser(_: string, month: string): Promise<FinancialSummary> { return { month, incomeCents: 0, expenseCents: 0, netCents: 0 }; } }
const input = { categoryId: expense.id, type: "expense" as const, amountCents: 1234, description: "Food", occurredOn: "2026-09-11" };
describe("TransactionService", () => { it("creates income and expenses for the authenticated user", async () => { const repository = new MemoryTransactions(); const service = new TransactionService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); await service.createForCurrentUser(input); await service.createForCurrentUser({ ...input, categoryId: income.id, type: "income" }); expect((await service.listForCurrentUser({}, 20)).map((row) => row.userId)).toEqual(["user-a", "user-a"]); }); it("edits and deletes an owned transaction", async () => { const repository = new MemoryTransactions(); const service = new TransactionService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); const created = await service.createForCurrentUser(input); expect((await service.updateForCurrentUser(created.id, { description: "Weekly food" })).description).toBe("Weekly food"); await service.deleteForCurrentUser(created.id); expect(await service.listForCurrentUser({}, 20)).toHaveLength(0); }); it("rejects category/type mismatches and cross-user mutations", async () => { const repository = new MemoryTransactions(); const userA = new TransactionService(repository, new MemoryCategories(), async () => ({ id: "user-a", email: "a@test.dev" })); const created = await userA.createForCurrentUser(input); await expect(userA.createForCurrentUser({ ...input, categoryId: income.id })).rejects.toMatchObject({ code: "VALIDATION_ERROR" }); const userB = new TransactionService(repository, new MemoryCategories(), async () => ({ id: "user-b", email: "b@test.dev" })); await expect(userB.updateForCurrentUser(created.id, { description: "attack" })).rejects.toMatchObject({ code: "NOT_FOUND" }); await expect(userB.deleteForCurrentUser(created.id)).rejects.toMatchObject({ code: "NOT_FOUND" }); }); });
